const JOBS = [
  {
    id: "job-001",
    code: "#001",
    title: "高一数学辅导（双休 / 可长期）",
    district: "南山区",
    area: "科技园",
    distance: "850m",
    grade: "高一",
    subject: "数学",
    price: "200",
    unit: "/小时",
    settlement: "周结",
    role: "大学生兼职",
    badge: "资质认证",
    badgeTone: "blue",
    publisher: "东莞二师兄",
    publisherRole: "平台认证顾问",
    description: "大二以上数学相关专业，讲课清晰。重点辅导几何与函数，最好有家教经验。",
    schedule: "周六、周日 14:00–16:00",
    address: "南山区科技园 · 地铁1号线附近",
    students: "1名男生，基础中等",
    x: 38,
    y: 23,
    color: "#3478f6"
  },
  {
    id: "job-002",
    code: "#002",
    title: "初二英语口语与听力强化",
    district: "福田区",
    area: "香蜜湖",
    distance: "3.2km",
    grade: "初二",
    subject: "英语",
    price: "350",
    unit: "/2小时",
    settlement: "月结",
    role: "专职老师",
    badge: "需持证",
    badgeTone: "blue",
    publisher: "东莞二师兄",
    publisherRole: "平台认证顾问",
    description: "专职英语老师，口语纯正。重点纠正发音，练习日常对话与中考真题。",
    schedule: "每周三、周五 19:00–21:00",
    address: "福田区香蜜湖街道",
    students: "1名女生，口语基础一般",
    x: 62,
    y: 49,
    color: "#574be7"
  },
  {
    id: "job-003",
    code: "#003",
    title: "周日少儿编程体验课推广",
    district: "宝安区",
    area: "壹方城",
    distance: "6.8km",
    grade: "兴趣课",
    subject: "编程",
    price: "180",
    unit: "/天+提成",
    settlement: "日结",
    role: "大学生兼职",
    badge: "限大学生",
    badgeTone: "red",
    publisher: "东莞二师兄",
    publisherRole: "平台认证顾问",
    description: "形象好、沟通能力强，在商场派发物料并引导家长扫码了解课程。",
    schedule: "周日 10:00–18:00",
    address: "宝安区壹方城商场",
    students: "线下推广，不涉及授课",
    x: 71,
    y: 66,
    color: "#28a866"
  },
  {
    id: "job-004",
    code: "#004",
    title: "小学五年级全科陪学",
    district: "宝安区",
    area: "西乡",
    distance: "8.1km",
    grade: "五年级",
    subject: "全科",
    price: "160",
    unit: "/2小时",
    settlement: "周结",
    role: "大学生兼职",
    badge: "耐心优先",
    badgeTone: "green",
    publisher: "林老师",
    publisherRole: "家长顾问",
    description: "陪伴完成作业，检查错题并制定每日复习计划，师范专业优先。",
    schedule: "周一至周四 18:30–20:30",
    address: "宝安区西乡街道",
    students: "1名男生，学习习惯待提升",
    x: 25,
    y: 70,
    color: "#ff9d2e"
  },
  {
    id: "job-005",
    code: "#005",
    title: "在线雅思口语陪练",
    district: "线上",
    area: "腾讯会议",
    distance: "线上",
    grade: "大学",
    subject: "英语",
    price: "120",
    unit: "/小时",
    settlement: "月结",
    role: "线上家教",
    badge: "可远程",
    badgeTone: "purple",
    publisher: "Mia学姐",
    publisherRole: "海外硕士",
    description: "按雅思口语题库进行模拟问答，课后给出表达与发音改进建议。",
    schedule: "工作日 20:00 后，时间可协商",
    address: "腾讯会议线上授课",
    students: "大学生，目标口语 6.5分",
    x: 48,
    y: 40,
    color: "#8c61df"
  },
  {
    id: "job-006",
    code: "#006",
    title: "初三物理中考冲刺",
    district: "龙华区",
    area: "红山",
    distance: "9.6km",
    grade: "初三",
    subject: "物理",
    price: "260",
    unit: "/2小时",
    settlement: "周结",
    role: "专职老师",
    badge: "教师资格证",
    badgeTone: "blue",
    publisher: "周老师",
    publisherRole: "教研负责人",
    description: "梳理力学、电学重点题型，针对模考错题查漏补缺并追踪提升。",
    schedule: "周六 09:00–11:00",
    address: "龙华区红山地铁站附近",
    students: "2人小组课，成绩中上",
    x: 79,
    y: 28,
    color: "#ef665c"
  }
];

const CATEGORIES = [
  { key: "大学生兼职", label: "大学生兼职", icon: "🎓", tone: "blue" },
  { key: "专职老师", label: "专职老师", icon: "✦", tone: "purple" },
  { key: "线上家教", label: "线上家教", icon: "▣", tone: "green" }
];

const DEFAULT_MESSAGES = [
  {
    id: "msg-001",
    type: "notice",
    title: "申请状态有更新",
    content: "你申请的“周日少儿编程体验课推广”已进入资料审核，预计 2 小时内反馈。",
    time: "10:26",
    unread: true,
    icon: "✓",
    tone: "green"
  },
  {
    id: "msg-002",
    type: "chat",
    title: "东莞二师兄",
    content: "你好，方便补充一下你的家教经历吗？",
    time: "昨天",
    unread: true,
    icon: "东",
    tone: "blue"
  },
  {
    id: "msg-003",
    type: "notice",
    title: "信誉分提升",
    content: "完成实名认证，信誉分 +10。完善教育经历还可继续加分。",
    time: "周一",
    unread: false,
    icon: "+",
    tone: "purple"
  },
  {
    id: "msg-004",
    type: "chat",
    title: "林老师",
    content: "西乡这份陪学单本周还能安排面试。",
    time: "周日",
    unread: false,
    icon: "林",
    tone: "orange"
  }
];

const FILTERS = {
  district: ["全市区", "南山区", "福田区", "宝安区", "龙华区", "线上"],
  grade: ["全部年级", "小学", "初中", "高中", "大学", "兴趣课"],
  subject: ["全部科目", "数学", "英语", "物理", "全科", "编程"],
  settlement: ["结算方式", "日结", "周结", "月结"]
};

function findJob(id) {
  return JOBS.find((job) => job.id === id);
}

module.exports = {
  CATEGORIES,
  DEFAULT_MESSAGES,
  FILTERS,
  JOBS,
  findJob
};
